name: Tailscale SSH deploy
author: FarisZR
description: Deploy files with a custom command using Tailscale SSH
inputs:
  remote_host:
    description: Remote host ie (user@host)
    required: true
  post_upload_command:
    description: sets command to run post upload
    required: false
  directory:
    description: specifies which directory to upload
    required: true
  remote_destination:
    description: directory to upload into
    default: "./"
runs:
  using: composite
  steps:
    - name: Check remote_host Empty
      if: ${{ inputs.remote_host == '' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::remote_host empty, Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets"
        exit 1
    - name: Check directory Empty
      if: ${{ inputs.directory == '' }}
      shell: bash
      run: |
        echo "::error title=⛔ error hint::directory empty, Maybe you need to populate it in the Secrets for your workflow, see more in https://docs.github.com/en/actions/security-guides/encrypted-secrets"
        exit 1
    - name: compress and upload
      shell: sh
      run: |
        tar cjvf - -C "$GITHUB_WORKSPACE" "$DIRECTORY" | ssh -o StrictHostKeyChecking=no "$REMOTE_HOST" "cd $REMOTE_DESTINATION && tar -xjvf -"
    - name: execute a post upload command if specified
      if: ${{ inputs.post_upload_command }}
      shell: sh
      run: |
        echo "Upload post command specified, runnig. $POST_UPLOAD_COMMAND"
        ssh -o StrictHostKeyChecking=no "$REMOTE_HOST" "eval $POST_UPLOAD_COMMAND"

branding:
  icon: terminal
  color: white